spring:

  h2:
    console:
      enabled: true

  datasource:
    initialize: true

  jpa:
    show-sql: true

server:
  context-path: /api
  connection-timeout: 30000
  tomcat:
    max-threads: 400
    accept-count: 800